# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:

# navigation menu
menu:
  - name: Home
    slug: home
    url: /
  - name: Archives
    slug: archives
    url: /archives
  - name: About
    slug: about
    url: /about

# widgets
widgets:
  - about
  - links
  - tagcloud
  - recent_comments

# Less
less:
  compress: true

# use url, not username
social:

# giscus
giscus:
  enable: false
  repo: jiaming0708/jiaming0708.github.io # Github repository name
  repo_id: MDEwOlJlcG9zaXRvcnk4Mjc2OTM4OQ== # Github repository id
  category: Q&A # Github discussion category
  category_id: DIC_kwDOBO717c4B_0N9 # Github discussion category id
  # Available values: pathname | url | title | og:title
  mapping: title
  # Available values: 0 | 1 
  reactions_enabled: 1
  # Available values: light | dark | dark_high_contrast | transparent_dark | preferred-color-scheme
  theme: light